-- Enable RLS on all tables missing policies

-- Enable RLS on each table
ALTER TABLE attorney_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE attorneys ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE avatars ENABLE ROW LEVEL SECURITY;
ALTER TABLE bail_bonds ENABLE ROW LEVEL SECURITY;
ALTER TABLE broadcast_restrictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_attorneys ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_charges ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_witnesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE charges ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE court_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE court_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE court_hearings ENABLE ROW LEVEL SECURITY;
ALTER TABLE defendants ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE family_bans ENABLE ROW LEVEL SECURITY;
ALTER TABLE hearing_attendees ENABLE ROW LEVEL SECURITY;
ALTER TABLE incarceration_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE incident_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE jail_cells ENABLE ROW LEVEL SECURITY;
ALTER TABLE jail_facilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE jail_inmates ENABLE ROW LEVEL SECURITY;
ALTER TABLE judges ENABLE ROW LEVEL SECURITY;
ALTER TABLE online_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE probation_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE prosecutors ENABLE ROW LEVEL SECURITY;
ALTER TABLE stream_kicks ENABLE ROW LEVEL SECURITY;
ALTER TABLE stream_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE tcps_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE verification_docs ENABLE ROW LEVEL SECURITY;
ALTER TABLE visitation_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE witnesses ENABLE ROW LEVEL SECURITY;

-- Create read policies for authenticated users
CREATE POLICY "Anyone can read" ON attorney_cases FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON attorneys FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON audit_log FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON avatars FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON bail_bonds FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON broadcast_restrictions FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON case_attorneys FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON case_charges FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON case_types FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON case_witnesses FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON charges FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON chat_blocks FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON court_cases FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON court_documents FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON court_hearings FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON defendants FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON events FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON evidence FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON family_bans FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON hearing_attendees FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON incarceration_records FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON incident_reports FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON jail_cells FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON jail_facilities FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON jail_inmates FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON judges FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON online_users FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON probation_records FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON prosecutors FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON stream_kicks FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON stream_settings FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON tcps_messages FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON users FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON verification_docs FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON visitation_records FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read" ON witnesses FOR SELECT USING (auth.role() = 'authenticated');

SELECT 'RLS enabled on 38 tables' AS result;