ALTER TABLE public.user_profiles 
ADD COLUMN IF NOT EXISTS message_cost INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS profile_view_cost INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS gender TEXT,
ADD COLUMN IF NOT EXISTS full_name TEXT;
