$c = [System.IO.File]::ReadAllText('ModActionsPopup.tsx')
$c = $c.Replace("Users,", "Users, Search,")
$c = $c.Replace("Mic, MicOff, AlertCircle, MessageSquareOff, LogOut, Power", "Mic, MicOff, AlertCircle, MessageSquareOff, LogOut, Power, Car")
$c = $c.Replace("is_staff?: boolean;", "is_staff?: boolean;\n}

interface UserSearchResult extends UserProfile {\n  is_staff?: boolean;\n  is_lead_officer?: boolean;\n  is_troll_officer?: boolean;\n}")
$c = $c.Replace("  const [isGiftModalOpen, setIsGiftModalOpen] = useState(false);`n  const [showBackgroundModal, setShowBackgroundModal] = useState(false);`n`n  // Arrest modal state", "  const [isGiftModalOpen, setIsGiftModalOpen] = useState(false);`n  const [showBackgroundModal, setShowBackgroundModal] = useState(false);`n`n  // User search state`n  const [searchQuery, setSearchQuery] = useState('');`n  const [searchResults, setSearchResults] = useState<UserSearchResult[]>([]);`n  const [isSearching, setIsSearching] = useState(false);`n  const [showSearchModal, setShowSearchModal] = useState(false);`n  const [searchError, setSearchError] = useState<string | null>(null);`n`n  // Suspend license state`n  const [showSuspendLicenseModal, setShowSuspendLicenseModal] = useState(false);`n  const [suspendDuration, setSuspendDuration] = useState(60);`n  const [suspendReason, setSuspendReason] = useState('');`n  const [isSuspending, setIsSuspending] = useState(false);`n`n  // Arrest modal state")
$c = $c.Replace("  { id: 'remove_officer',", "  { id: 'suspend_license', label: 'Suspend License', icon: Car, color: 'text-yellow-500', description: 'Suspend driver license' },`n  { id: 'remove_officer',")
$c = $c.Replace("          </button>`n        </div>`n`n        {/* Content */}", "          </button>`n        </div>`n`n        {activeTab -eq 'mod' -and '<div className=\"px-4 pb-3\"><div className=\"relative\"><Search className=\"absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500\" /><input type=\"text\" placeholder=\"Search users...\" value={searchQuery} onChange={e => setSearchQuery(e.target.value)} className=\"w-full bg-slate-800 border border-slate-700 rounded-lg pl-10 pr-4 py-2 text-white text-sm\" /></div>' + (if (searchQuery) { '<button onClick={handleUserSearch} className=\"w-full mt-2 py-1.5 bg-slate-700 text-slate-300 rounded-lg text-xs hover:bg-slate-600\">Search Users</button>' } else { '' }) + '</div>'}")
$c = $c.Replace("    setShowBackgroundModal(true);`n  };`n`n  const handleAction = (actionId: string) => {", "    setShowBackgroundModal(true);`n  };`n`n  const handleUserSearch = async () => { if (!searchQuery) return; setIsSearching(true); try { $r = await fetch('/api/users/search?q=' + [System.Web.HttpUtility]::UrlEncode(searchQuery) + '&limit=10'); $d = await $r.json(); setSearchResults($d.users || []); setShowSearchModal(true); } catch { console.error('Search error:', $_); setSearchError('Failed to search users'); } finally { setIsSearching(false); } };`n`n  const handleSuspendLicense = async () => { if (!targetUserId || !currentUserId || !suspendReason) { toast.error('Please provide a reason'); return; } setIsSuspending(true); try { $res = await supabase.rpc('admin_suspend_license_with_duration', @{ p_target_user_id = targetUserId; p_suspended_by = currentUserId; p_reason = suspendReason; p_duration_minutes = suspendDuration }); if ($res.error) { throw $res.error; } toast.success(targetUsername + ' license suspended for ' + suspendDuration + ' min'); setShowSuspendLicenseModal(false); setSuspendReason(''); setSuspendDuration(60); onClose(); } catch { console.error('Error suspending license:', $_); toast.error('Failed to suspend license'); } finally { setIsSuspending(false); } };`n`n  const handleAction = (actionId: string) => {")
$c = $c.Replace("      case 'remove_officer':", "      case 'suspend_license': setShowSuspendLicenseModal(true); break;\n      case 'remove_officer':")
$c = $c.Replace("</AnimatePresence>", "</AnimatePresence>`n{showSuspendLicenseModal -and '<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className=\"absolute inset-0 bg-slate-900/95 flex items-center justify-center p-4 z-50\"><div className=\"bg-slate-800 border border-yellow-500/30 rounded-xl p-4 w-full max-w-sm\"><div className=\"flex items-center gap-2 mb-4\"><Car className=\"w-5 h-5 text-yellow-400\" /><h3 className=\"text-white font-semibold\">Suspend License</h3></div><div className=\"space-y-3\"><div><label className=\"text-sm text-slate-400 block mb-1\">Duration</label><div className=\"grid grid-cols-4 gap-2\">' + @(5,15,30,60) % { '<button onClick={()=>setSuspendDuration($_)} className={\"py-2 rounded-lg text-xs font-medium transition-colors ' + (if ($suspendDuration -eq $_) { 'bg-yellow-500/20 text-yellow-400 border border-yellow-500/50' } else { 'bg-slate-900 text-slate-400 border border-slate-700 hover:border-slate-600' }) + '\"}>' + (if ($_ -lt 60) { \"${_}m\" } else { \"$($_/60)h\" }) + '</button>' } + '</div></div><div><label className=\"text-sm text-slate-400 block mb-1\">Reason</label><input type=\"text\" value={suspendReason} onChange={e=>setSuspendReason(e.target.value)} placeholder=\"e.g., DUI\" className=\"w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-white text-sm\" /></div><p className=\"text-xs text-slate-500\">User cannot start broadcasts or join seats while suspended. Must have active insurance.</p><div className=\"flex gap-2 mt-4\"><button onClick={()=>setShowSuspendLicenseModal(false)} className=\"flex-1 py-2 bg-slate-700 text-white rounded-lg text-sm hover:bg-slate-600\">Cancel</button><button onClick={handleSuspendLicense} disabled={isSuspending -or !$suspendReason} className=\"flex-1 py-2 bg-yellow-600 text-white rounded-lg text-sm hover:bg-yellow-500 disabled:opacity-50\">' + (if ($isSuspending) { 'Suspending...' } else { 'Suspend License' }) + '</button></div></div></div></motion.div>}")
[System.IO.File]::WriteAllText('ModActionsPopup.tsx', $c)
Write-Output ("Done - " + $c.Length)
